[package]
name = "aoc2023"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
#recap = "0.1.1"
#serde = "1.0.130"
#serde_derive = "1.0.130"
#itertools = "0.10.3"
#nom = "7.1.0"
