use regex::Regex;

pub fn solve_part_1() -> u32 {
    let all_aunts = input();
    let children = 3;
    let cats = 7;
    let samoyeds = 2;
    let pomeranians = 3;
    let akitas = 0;
    let vizslas = 0;
    let goldfish = 5;
    let trees = 3;
    let cars = 2;
    let perfumes = 1;
    let matches: Vec<_> = all_aunts
        .into_iter()
        .enumerate()
        .filter(|(_, a)| a.children.map_or_else(|| true, |v| v == children))
        .filter(|(_, a)| a.cats.map_or_else(|| true, |v| v == cats))
        .filter(|(_, a)| a.samoyeds.map_or_else(|| true, |v| v == samoyeds))
        .filter(|(_, a)| a.pomeranians.map_or_else(|| true, |v| v == pomeranians))
        .filter(|(_, a)| a.akitas.map_or_else(|| true, |v| v == akitas))
        .filter(|(_, a)| a.vizslas.map_or_else(|| true, |v| v == vizslas))
        .filter(|(_, a)| a.goldfish.map_or_else(|| true, |v| v == goldfish))
        .filter(|(_, a)| a.trees.map_or_else(|| true, |v|  v == trees))
        .filter(|(_, a)| a.cars.map_or_else(|| true, |v| v == cars))
        .filter(|(_, a)| a.perfumes.map_or_else(|| true, |v| v == perfumes))
        // .map(|(i, _)| i)
        .collect();
    assert_eq!(matches.len(), 1);
    (matches[0].0 as u32) + 1
}

pub fn solve_part_2() -> u32 {
    let all_aunts = input();
    let children = 3;
    let cats = 7;
    let samoyeds = 2;
    let pomeranians = 3;
    let akitas = 0;
    let vizslas = 0;
    let goldfish = 5;
    let trees = 3;
    let cars = 2;
    let perfumes = 1;
    let matches: Vec<_> = all_aunts
        .into_iter()
        .enumerate()
        .filter(|(_, a)| a.children.map_or_else(|| true, |v| v == children))
        .filter(|(_, a)| a.cats.map_or_else(|| true, |v| v > cats))
        .filter(|(_, a)| a.samoyeds.map_or_else(|| true, |v| v == samoyeds))
        .filter(|(_, a)| a.pomeranians.map_or_else(|| true, |v| v < pomeranians))
        .filter(|(_, a)| a.akitas.map_or_else(|| true, |v| v == akitas))
        .filter(|(_, a)| a.vizslas.map_or_else(|| true, |v| v == vizslas))
        .filter(|(_, a)| a.goldfish.map_or_else(|| true, |v| v < goldfish))
        .filter(|(_, a)| a.trees.map_or_else(|| true, |v| v > trees))
        .filter(|(_, a)| a.cars.map_or_else(|| true, |v| v == cars))
        .filter(|(_, a)| a.perfumes.map_or_else(|| true, |v| v == perfumes))
        // .map(|(i, _)| i)
        .collect();
    assert_eq!(matches.len(), 1);
    (matches[0].0 as u32) + 1
}

#[derive(Debug)]
struct AuntSue {
    children: Option<u8>,
    cats: Option<u8>,
    samoyeds: Option<u8>,
    pomeranians: Option<u8>,
    akitas: Option<u8>,
    vizslas: Option<u8>,
    goldfish: Option<u8>,
    trees: Option<u8>,
    cars: Option<u8>,
    perfumes: Option<u8>,
}
lazy_static! {
    static ref CHILDREN_REGEX: Regex = Regex::new(r"children: (\d+)").unwrap();
    static ref CATS_REGEX: Regex = Regex::new(r"cats: (\d+)").unwrap();
    static ref SAMOYEDS_REGEX: Regex = Regex::new(r"samoyeds: (\d+)").unwrap();
    static ref POMERANIANS_REGEX: Regex = Regex::new(r"pomeranions: (\d+)").unwrap();
    static ref AKITAS_REGEX: Regex = Regex::new(r"akitas: (\d+)").unwrap();
    static ref VIZSLAS_REGEX: Regex = Regex::new(r"vizslas: (\d+)").unwrap();
    static ref GOLDFISH_REGEX: Regex = Regex::new(r"goldfish: (\d+)").unwrap();
    static ref TREES_REGEX: Regex = Regex::new(r"trees: (\d+)").unwrap();
    static ref CARS_REGEX: Regex = Regex::new(r"cars: (\d+)").unwrap();
    static ref PERFUMES_REGEX: Regex = Regex::new(r"perfumes: (\d+)").unwrap();
}

impl From<&str> for AuntSue {
    fn from(s: &str) -> Self {
        AuntSue {
            children: CHILDREN_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            cats: CATS_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            samoyeds: SAMOYEDS_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            pomeranians: POMERANIANS_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            akitas: AKITAS_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            vizslas: VIZSLAS_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            goldfish: GOLDFISH_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            trees: TREES_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            cars: CARS_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
            perfumes: PERFUMES_REGEX
                .captures(s)
                .map(|s| s[1].parse::<u8>().expect("Error")),
        }
    }
}

fn input() -> Vec<AuntSue> {
    vec![
        AuntSue::from(" children: 1, cars: 8, vizslas: 7"),
        AuntSue::from(" akitas: 10, perfumes: 10, children: 5"),
        AuntSue::from(" cars: 5, pomeranians: 4, vizslas: 1"),
        AuntSue::from(" goldfish: 5, children: 8, perfumes: 3"),
        AuntSue::from(" vizslas: 2, akitas: 7, perfumes: 6"),
        AuntSue::from(" vizslas: 0, akitas: 1, perfumes: 2"),
        AuntSue::from(" perfumes: 8, cars: 4, goldfish: 10"),
        AuntSue::from(" perfumes: 7, children: 2, cats: 1"),
        AuntSue::from(" pomeranians: 3, goldfish: 10, trees: 10"),
        AuntSue::from(" akitas: 7, trees: 8, pomeranians: 4"),
        AuntSue::from(" goldfish: 1, perfumes: 4, cars: 6"),
        AuntSue::from(" samoyeds: 6, trees: 6, perfumes: 2"),
        AuntSue::from(" akitas: 10, pomeranians: 0, vizslas: 2"),
        AuntSue::from(" cars: 2, perfumes: 3, children: 4"),
        AuntSue::from(" goldfish: 2, children: 8, cars: 5"),
        AuntSue::from(" goldfish: 9, cars: 0, vizslas: 5"),
        AuntSue::from(" cats: 5, trees: 6, perfumes: 6"),
        AuntSue::from(" cars: 0, perfumes: 8, pomeranians: 7"),
        AuntSue::from(" trees: 2, goldfish: 5, perfumes: 4"),
        AuntSue::from(" akitas: 4, vizslas: 4, trees: 0"),
        AuntSue::from(" pomeranians: 7, trees: 0, goldfish: 10"),
        AuntSue::from(" cars: 4, vizslas: 0, perfumes: 3"),
        AuntSue::from(" vizslas: 8, trees: 1, akitas: 2"),
        AuntSue::from(" children: 7, trees: 0, akitas: 1"),
        AuntSue::from(" goldfish: 3, akitas: 2, trees: 2"),
        AuntSue::from(" pomeranians: 4, vizslas: 4, samoyeds: 2"),
        AuntSue::from(" cars: 0, trees: 8, akitas: 5"),
        AuntSue::from(" perfumes: 6, cats: 0, cars: 2"),
        AuntSue::from(" trees: 7, akitas: 1, vizslas: 1"),
        AuntSue::from(" perfumes: 9, cars: 9, trees: 10"),
        AuntSue::from(" pomeranians: 5, akitas: 9, samoyeds: 1"),
        AuntSue::from(" pomeranians: 10, vizslas: 5, goldfish: 5"),
        AuntSue::from(" vizslas: 2, akitas: 3, trees: 7"),
        AuntSue::from(" goldfish: 10, perfumes: 0, samoyeds: 7"),
        AuntSue::from(" akitas: 6, cats: 7, perfumes: 10"),
        AuntSue::from(" pomeranians: 8, vizslas: 7, akitas: 6"),
        AuntSue::from(" goldfish: 2, cars: 10, children: 7"),
        AuntSue::from(" goldfish: 2, perfumes: 3, cars: 7"),
        AuntSue::from(" trees: 9, vizslas: 10, cars: 5"),
        AuntSue::from(" goldfish: 1, pomeranians: 0, trees: 2"),
        AuntSue::from(" trees: 2, goldfish: 6, vizslas: 3"),
        AuntSue::from(" akitas: 1, cars: 3, vizslas: 3"),
        AuntSue::from(" akitas: 1, pomeranians: 1, vizslas: 3"),
        AuntSue::from(" goldfish: 7, akitas: 3, vizslas: 10"),
        AuntSue::from(" akitas: 8, samoyeds: 8, goldfish: 2"),
        AuntSue::from(" trees: 0, vizslas: 4, cars: 9"),
        AuntSue::from(" cars: 9, trees: 10, perfumes: 4"),
        AuntSue::from(" akitas: 0, vizslas: 5, perfumes: 4"),
        AuntSue::from(" goldfish: 9, trees: 1, cars: 4"),
        AuntSue::from(" goldfish: 2, perfumes: 5, cars: 2"),
        AuntSue::from(" samoyeds: 1, goldfish: 2, perfumes: 7"),
        AuntSue::from(" cars: 0, perfumes: 4, goldfish: 8"),
        AuntSue::from(" goldfish: 9, vizslas: 2, akitas: 9"),
        AuntSue::from(" trees: 1, goldfish: 9, children: 5"),
        AuntSue::from(" cars: 0, akitas: 5, trees: 4"),
        AuntSue::from(" trees: 4, samoyeds: 5, children: 9"),
        AuntSue::from(" children: 0, vizslas: 8, cars: 3"),
        AuntSue::from(" trees: 4, pomeranians: 5, akitas: 5"),
        AuntSue::from(" vizslas: 10, cats: 3, children: 2"),
        AuntSue::from(" cats: 6, vizslas: 2, cars: 2"),
        AuntSue::from(" akitas: 1, vizslas: 0, children: 4"),
        AuntSue::from(" akitas: 4, trees: 9, children: 10"),
        AuntSue::from(" pomeranians: 6, vizslas: 6, cars: 4"),
        AuntSue::from(" perfumes: 8, pomeranians: 1, children: 8"),
        AuntSue::from(" perfumes: 3, goldfish: 6, trees: 5"),
        AuntSue::from(" goldfish: 10, akitas: 8, vizslas: 4"),
        AuntSue::from(" vizslas: 10, samoyeds: 3, trees: 2"),
        AuntSue::from(" samoyeds: 4, cars: 7, perfumes: 3"),
        AuntSue::from(" perfumes: 2, goldfish: 0, trees: 2"),
        AuntSue::from(" trees: 8, vizslas: 7, akitas: 6"),
        AuntSue::from(" cars: 2, children: 7, perfumes: 3"),
        AuntSue::from(" cars: 1, akitas: 9, perfumes: 0"),
        AuntSue::from(" vizslas: 4, akitas: 7, cars: 5"),
        AuntSue::from(" samoyeds: 3, cars: 3, akitas: 2"),
        AuntSue::from(" trees: 2, cars: 1, vizslas: 7"),
        AuntSue::from(" samoyeds: 9, perfumes: 1, trees: 6"),
        AuntSue::from(" trees: 6, perfumes: 10, cars: 7"),
        AuntSue::from(" trees: 0, children: 8, vizslas: 5"),
        AuntSue::from(" vizslas: 0, trees: 0, samoyeds: 1"),
        AuntSue::from(" trees: 6, goldfish: 8, perfumes: 0"),
        AuntSue::from(" samoyeds: 8, pomeranians: 6, akitas: 5"),
        AuntSue::from(" vizslas: 6, perfumes: 9, akitas: 4"),
        AuntSue::from(" cats: 0, vizslas: 3, pomeranians: 10"),
        AuntSue::from(" cars: 4, perfumes: 6, samoyeds: 5"),
        AuntSue::from(" vizslas: 7, trees: 5, goldfish: 7"),
        AuntSue::from(" goldfish: 2, trees: 2, vizslas: 1"),
        AuntSue::from(" trees: 6, goldfish: 10, pomeranians: 4"),
        AuntSue::from(" vizslas: 1, akitas: 0, perfumes: 8"),
        AuntSue::from(" goldfish: 8, akitas: 3, vizslas: 7"),
        AuntSue::from(" vizslas: 9, akitas: 7, perfumes: 9"),
        AuntSue::from(" children: 7, cars: 7, trees: 9"),
        AuntSue::from(" vizslas: 10, akitas: 8, goldfish: 1"),
        AuntSue::from(" goldfish: 7, vizslas: 2, pomeranians: 0"),
        AuntSue::from(" cats: 2, samoyeds: 6, pomeranians: 3"),
        AuntSue::from(" samoyeds: 4, children: 4, pomeranians: 10"),
        AuntSue::from(" pomeranians: 9, cats: 1, goldfish: 3"),
        AuntSue::from(" trees: 1, akitas: 6, goldfish: 1"),
        AuntSue::from(" vizslas: 7, akitas: 2, perfumes: 7"),
        AuntSue::from(" pomeranians: 6, perfumes: 2, trees: 1"),
        AuntSue::from(" cars: 3, children: 9, trees: 10"),
        AuntSue::from(" children: 0, perfumes: 0, vizslas: 3"),
        AuntSue::from(" cars: 4, goldfish: 5, children: 2"),
        AuntSue::from(" pomeranians: 3, perfumes: 7, cats: 8"),
        AuntSue::from(" akitas: 0, perfumes: 5, vizslas: 5"),
        AuntSue::from(" akitas: 7, vizslas: 2, samoyeds: 8"),
        AuntSue::from(" goldfish: 7, perfumes: 0, cats: 8"),
        AuntSue::from(" cats: 6, pomeranians: 9, cars: 6"),
        AuntSue::from(" akitas: 3, vizslas: 10, cats: 5"),
        AuntSue::from(" akitas: 10, perfumes: 2, cars: 7"),
        AuntSue::from(" goldfish: 7, pomeranians: 1, trees: 1"),
        AuntSue::from(" akitas: 10, samoyeds: 6, vizslas: 6"),
        AuntSue::from(" cats: 6, akitas: 7, trees: 9"),
        AuntSue::from(" akitas: 1, trees: 9, vizslas: 8"),
        AuntSue::from(" vizslas: 2, cats: 1, cars: 4"),
        AuntSue::from(" akitas: 0, trees: 5, goldfish: 7"),
        AuntSue::from(" goldfish: 2, trees: 10, akitas: 2"),
        AuntSue::from(" cars: 4, goldfish: 10, perfumes: 5"),
        AuntSue::from(" cars: 5, perfumes: 6, trees: 0"),
        AuntSue::from(" perfumes: 5, vizslas: 1, cats: 0"),
        AuntSue::from(" perfumes: 8, akitas: 9, vizslas: 4"),
        AuntSue::from(" samoyeds: 2, vizslas: 7, perfumes: 6"),
        AuntSue::from(" children: 6, trees: 9, perfumes: 2"),
        AuntSue::from(" cars: 7, akitas: 0, pomeranians: 0"),
        AuntSue::from(" akitas: 7, cats: 8, vizslas: 5"),
        AuntSue::from(" goldfish: 3, trees: 1, cars: 4"),
        AuntSue::from(" cars: 4, perfumes: 3, akitas: 0"),
        AuntSue::from(" children: 10, vizslas: 5, akitas: 9"),
        AuntSue::from(" akitas: 3, samoyeds: 2, cats: 8"),
        AuntSue::from(" cats: 8, akitas: 1, vizslas: 8"),
        AuntSue::from(" trees: 4, cars: 6, perfumes: 6"),
        AuntSue::from(" akitas: 7, perfumes: 6, goldfish: 9"),
        AuntSue::from(" akitas: 6, vizslas: 7, trees: 1"),
        AuntSue::from(" akitas: 5, vizslas: 7, children: 9"),
        AuntSue::from(" cars: 8, goldfish: 4, pomeranians: 4"),
        AuntSue::from(" samoyeds: 1, pomeranians: 6, akitas: 4"),
        AuntSue::from(" perfumes: 10, goldfish: 1, cars: 3"),
        AuntSue::from(" cars: 3, samoyeds: 6, vizslas: 7"),
        AuntSue::from(" samoyeds: 10, akitas: 3, perfumes: 4"),
        AuntSue::from(" perfumes: 10, vizslas: 2, goldfish: 7"),
        AuntSue::from(" samoyeds: 7, cars: 1, trees: 2"),
        AuntSue::from(" children: 6, cats: 5, cars: 9"),
        AuntSue::from(" cats: 0, trees: 1, akitas: 10"),
        AuntSue::from(" samoyeds: 4, cars: 0, children: 7"),
        AuntSue::from(" trees: 0, cars: 4, perfumes: 8"),
        AuntSue::from(" goldfish: 7, cars: 5, trees: 1"),
        AuntSue::from(" perfumes: 7, cars: 7, goldfish: 0"),
        AuntSue::from(" trees: 2, goldfish: 7, vizslas: 5"),
        AuntSue::from(" samoyeds: 8, perfumes: 1, trees: 0"),
        AuntSue::from(" vizslas: 2, samoyeds: 5, trees: 0"),
        AuntSue::from(" akitas: 4, perfumes: 4, pomeranians: 2"),
        AuntSue::from(" trees: 2, cars: 0, goldfish: 10"),
        AuntSue::from(" goldfish: 7, vizslas: 0, trees: 0"),
        AuntSue::from(" children: 9, cats: 0, pomeranians: 10"),
        AuntSue::from(" cars: 6, goldfish: 10, akitas: 5"),
        AuntSue::from(" perfumes: 9, trees: 2, akitas: 3"),
        AuntSue::from(" pomeranians: 9, perfumes: 5, cars: 9"),
        AuntSue::from(" akitas: 0, trees: 2, cars: 7"),
        AuntSue::from(" goldfish: 10, trees: 8, akitas: 7"),
        AuntSue::from(" akitas: 5, trees: 10, cars: 10"),
        AuntSue::from(" akitas: 3, trees: 5, cars: 8"),
        AuntSue::from(" samoyeds: 2, cars: 7, perfumes: 4"),
        AuntSue::from(" cars: 6, vizslas: 10, pomeranians: 5"),
        AuntSue::from(" cars: 10, perfumes: 6, vizslas: 9"),
        AuntSue::from(" pomeranians: 7, cars: 4, vizslas: 2"),
        AuntSue::from(" goldfish: 9, vizslas: 3, trees: 1"),
        AuntSue::from(" goldfish: 1, samoyeds: 3, trees: 1"),
        AuntSue::from(" vizslas: 4, goldfish: 7, cats: 5"),
        AuntSue::from(" children: 1, cars: 5, samoyeds: 7"),
        AuntSue::from(" trees: 1, samoyeds: 3, goldfish: 6"),
        AuntSue::from(" goldfish: 2, cars: 3, perfumes: 9"),
        AuntSue::from(" cars: 4, goldfish: 0, trees: 6"),
        AuntSue::from(" cats: 8, perfumes: 6, trees: 1"),
        AuntSue::from(" akitas: 9, goldfish: 7, cars: 10"),
        AuntSue::from(" vizslas: 2, trees: 0, akitas: 1"),
        AuntSue::from(" perfumes: 3, vizslas: 8, akitas: 4"),
        AuntSue::from(" perfumes: 0, akitas: 6, goldfish: 3"),
        AuntSue::from(" perfumes: 6, children: 1, goldfish: 10"),
        AuntSue::from(" cars: 5, vizslas: 3, children: 10"),
        AuntSue::from(" perfumes: 3, trees: 8, cats: 9"),
        AuntSue::from(" perfumes: 8, vizslas: 4, trees: 7"),
        AuntSue::from(" perfumes: 7, vizslas: 9, samoyeds: 4"),
        AuntSue::from(" vizslas: 9, trees: 4, pomeranians: 4"),
        AuntSue::from(" trees: 9, cars: 3, goldfish: 5"),
        AuntSue::from(" perfumes: 2, cars: 4, vizslas: 3"),
        AuntSue::from(" children: 10, akitas: 10, cats: 9"),
        AuntSue::from(" cars: 5, samoyeds: 0, trees: 0"),
        AuntSue::from(" trees: 2, goldfish: 3, cars: 4"),
        AuntSue::from(" goldfish: 3, vizslas: 1, cats: 6"),
        AuntSue::from(" trees: 2, pomeranians: 10, cars: 7"),
        AuntSue::from(" perfumes: 10, akitas: 3, samoyeds: 0"),
        AuntSue::from(" cats: 5, vizslas: 6, akitas: 6"),
        AuntSue::from(" samoyeds: 5, trees: 1, perfumes: 8"),
        AuntSue::from(" pomeranians: 0, akitas: 9, cats: 0"),
        AuntSue::from(" trees: 1, goldfish: 0, perfumes: 10"),
        AuntSue::from(" perfumes: 2, akitas: 7, cars: 5"),
        AuntSue::from(" perfumes: 5, samoyeds: 8, cars: 1"),
        AuntSue::from(" vizslas: 2, pomeranians: 9, trees: 1"),
        AuntSue::from(" trees: 8, vizslas: 6, children: 8"),
        AuntSue::from(" pomeranians: 4, cars: 7, vizslas: 5"),
        AuntSue::from(" trees: 0, perfumes: 10, akitas: 10"),
        AuntSue::from(" cats: 9, akitas: 4, vizslas: 0"),
        AuntSue::from(" goldfish: 9, pomeranians: 9, cats: 6"),
        AuntSue::from(" cars: 5, perfumes: 5, trees: 2"),
        AuntSue::from(" pomeranians: 7, children: 2, akitas: 6"),
        AuntSue::from(" samoyeds: 7, pomeranians: 7, children: 6"),
        AuntSue::from(" trees: 1, cars: 1, pomeranians: 4"),
        AuntSue::from(" goldfish: 2, perfumes: 5, trees: 0"),
        AuntSue::from(" perfumes: 2, samoyeds: 4, trees: 1"),
        AuntSue::from(" cars: 8, perfumes: 6, goldfish: 9"),
        AuntSue::from(" perfumes: 4, cars: 8, samoyeds: 3"),
        AuntSue::from(" perfumes: 2, cars: 8, trees: 9"),
        AuntSue::from(" trees: 7, perfumes: 2, akitas: 5"),
        AuntSue::from(" children: 3, goldfish: 5, vizslas: 0"),
        AuntSue::from(" akitas: 6, goldfish: 0, children: 0"),
        AuntSue::from(" trees: 8, akitas: 3, goldfish: 1"),
        AuntSue::from(" goldfish: 6, perfumes: 8, akitas: 3"),
        AuntSue::from(" children: 7, trees: 2, vizslas: 6"),
        AuntSue::from(" goldfish: 8, samoyeds: 4, pomeranians: 6"),
        AuntSue::from(" goldfish: 8, samoyeds: 0, children: 9"),
        AuntSue::from(" perfumes: 1, cars: 8, vizslas: 6"),
        AuntSue::from(" perfumes: 9, cars: 10, children: 10"),
        AuntSue::from(" perfumes: 9, vizslas: 1, trees: 0"),
        AuntSue::from(" goldfish: 1, akitas: 2, vizslas: 8"),
        AuntSue::from(" samoyeds: 8, akitas: 7, vizslas: 4"),
        AuntSue::from(" goldfish: 1, cars: 4, perfumes: 10"),
        AuntSue::from(" goldfish: 9, trees: 4, perfumes: 5"),
        AuntSue::from(" vizslas: 5, trees: 4, goldfish: 7"),
        AuntSue::from(" cars: 1, cats: 10, perfumes: 4"),
        AuntSue::from(" vizslas: 8, cars: 10, akitas: 4"),
        AuntSue::from(" cats: 1, children: 8, vizslas: 3"),
        AuntSue::from(" perfumes: 7, cats: 6, samoyeds: 7"),
        AuntSue::from(" cars: 3, children: 9, perfumes: 7"),
        AuntSue::from(" vizslas: 1, samoyeds: 2, children: 2"),
        AuntSue::from(" trees: 1, samoyeds: 8, children: 2"),
        AuntSue::from(" trees: 6, akitas: 9, goldfish: 7"),
        AuntSue::from(" children: 10, trees: 0, samoyeds: 8"),
        AuntSue::from(" pomeranians: 4, trees: 1, goldfish: 2"),
        AuntSue::from(" vizslas: 4, akitas: 2, cars: 0"),
        AuntSue::from(" goldfish: 9, cars: 10, perfumes: 4"),
        AuntSue::from(" perfumes: 3, vizslas: 6, trees: 6"),
        AuntSue::from(" pomeranians: 6, akitas: 4, trees: 2"),
        AuntSue::from(" cars: 8, perfumes: 5, children: 7"),
        AuntSue::from(" trees: 4, perfumes: 7, cars: 3"),
        AuntSue::from(" perfumes: 6, akitas: 1, vizslas: 7"),
        AuntSue::from(" akitas: 3, perfumes: 9, samoyeds: 0"),
        AuntSue::from(" pomeranians: 3, vizslas: 9, samoyeds: 1"),
        AuntSue::from(" cars: 0, goldfish: 7, cats: 2"),
        AuntSue::from(" trees: 5, goldfish: 6, perfumes: 3"),
        AuntSue::from(" trees: 0, pomeranians: 7, perfumes: 9"),
        AuntSue::from(" cars: 9, trees: 1, goldfish: 10"),
        AuntSue::from(" perfumes: 3, cars: 8, trees: 7"),
        AuntSue::from(" cars: 5, akitas: 7, trees: 8"),
        AuntSue::from(" perfumes: 7, akitas: 3, trees: 8"),
        AuntSue::from(" goldfish: 8, samoyeds: 1, vizslas: 7"),
        AuntSue::from(" perfumes: 3, cars: 4, children: 6"),
        AuntSue::from(" perfumes: 9, trees: 8, children: 7"),
        AuntSue::from(" trees: 8, children: 6, cars: 4"),
        AuntSue::from(" vizslas: 1, trees: 10, goldfish: 9"),
        AuntSue::from(" vizslas: 5, trees: 6, goldfish: 9"),
        AuntSue::from(" trees: 0, goldfish: 6, cars: 7"),
        AuntSue::from(" cars: 1, perfumes: 4, goldfish: 9"),
        AuntSue::from(" cars: 7, goldfish: 9, cats: 9"),
        AuntSue::from(" cars: 0, children: 5, goldfish: 8"),
        AuntSue::from(" cars: 2, akitas: 8, trees: 0"),
        AuntSue::from(" perfumes: 9, children: 8, samoyeds: 7"),
        AuntSue::from(" cats: 1, children: 1, vizslas: 10"),
        AuntSue::from(" vizslas: 8, children: 2, trees: 6"),
        AuntSue::from(" akitas: 10, vizslas: 3, cats: 2"),
        AuntSue::from(" children: 4, goldfish: 1, cats: 6"),
        AuntSue::from(" vizslas: 5, cars: 9, akitas: 9"),
        AuntSue::from(" vizslas: 5, children: 4, akitas: 3"),
        AuntSue::from(" cars: 1, goldfish: 0, vizslas: 0"),
        AuntSue::from(" goldfish: 10, samoyeds: 1, akitas: 2"),
        AuntSue::from(" goldfish: 10, children: 2, pomeranians: 0"),
        AuntSue::from(" children: 0, vizslas: 1, samoyeds: 6"),
        AuntSue::from(" children: 1, vizslas: 3, samoyeds: 1"),
        AuntSue::from(" perfumes: 4, cats: 6, children: 10"),
        AuntSue::from(" pomeranians: 7, goldfish: 3, cars: 4"),
        AuntSue::from(" perfumes: 5, goldfish: 9, trees: 7"),
        AuntSue::from(" goldfish: 6, trees: 5, perfumes: 8"),
        AuntSue::from(" cars: 2, akitas: 1, vizslas: 7"),
        AuntSue::from(" vizslas: 4, akitas: 3, children: 8"),
        AuntSue::from(" pomeranians: 8, akitas: 9, vizslas: 4"),
        AuntSue::from(" samoyeds: 10, trees: 10, pomeranians: 2"),
        AuntSue::from(" akitas: 9, perfumes: 7, goldfish: 6"),
        AuntSue::from(" akitas: 2, vizslas: 7, goldfish: 10"),
        AuntSue::from(" pomeranians: 8, cars: 6, samoyeds: 5"),
        AuntSue::from(" pomeranians: 1, trees: 0, goldfish: 0"),
        AuntSue::from(" trees: 10, samoyeds: 1, children: 0"),
        AuntSue::from(" cats: 10, samoyeds: 6, trees: 0"),
        AuntSue::from(" vizslas: 9, trees: 6, goldfish: 5"),
        AuntSue::from(" cats: 4, perfumes: 8, cars: 3"),
        AuntSue::from(" goldfish: 10, perfumes: 10, cats: 0"),
        AuntSue::from(" cats: 7, trees: 6, akitas: 4"),
        AuntSue::from(" vizslas: 8, cars: 1, akitas: 6"),
        AuntSue::from(" vizslas: 5, akitas: 10, trees: 1"),
        AuntSue::from(" pomeranians: 8, samoyeds: 5, vizslas: 4"),
        AuntSue::from(" perfumes: 10, children: 5, vizslas: 2"),
        AuntSue::from(" cars: 10, akitas: 7, cats: 5"),
        AuntSue::from(" trees: 1, perfumes: 7, cars: 7"),
        AuntSue::from(" cars: 9, vizslas: 1, perfumes: 3"),
        AuntSue::from(" perfumes: 9, vizslas: 1, akitas: 5"),
        AuntSue::from(" akitas: 9, trees: 1, goldfish: 10"),
        AuntSue::from(" children: 10, vizslas: 6, pomeranians: 8"),
        AuntSue::from(" trees: 3, goldfish: 6, cats: 9"),
        AuntSue::from(" cars: 5, perfumes: 9, vizslas: 5"),
        AuntSue::from(" children: 0, goldfish: 7, trees: 2"),
        AuntSue::from(" trees: 9, samoyeds: 4, cars: 0"),
        AuntSue::from(" cats: 8, vizslas: 2, perfumes: 3"),
        AuntSue::from(" cars: 6, pomeranians: 6, vizslas: 6"),
        AuntSue::from(" vizslas: 6, akitas: 7, cats: 10"),
        AuntSue::from(" trees: 0, goldfish: 7, cars: 0"),
        AuntSue::from(" perfumes: 5, akitas: 5, cars: 2"),
        AuntSue::from(" akitas: 10, vizslas: 3, samoyeds: 8"),
        AuntSue::from(" cars: 3, perfumes: 1, goldfish: 8"),
        AuntSue::from(" pomeranians: 6, goldfish: 9, perfumes: 1"),
        AuntSue::from(" goldfish: 4, akitas: 6, cars: 2"),
        AuntSue::from(" perfumes: 8, vizslas: 8, akitas: 0"),
        AuntSue::from(" akitas: 10, cars: 5, vizslas: 6"),
        AuntSue::from(" vizslas: 4, akitas: 3, cats: 4"),
        AuntSue::from(" goldfish: 4, akitas: 8, cars: 8"),
        AuntSue::from(" pomeranians: 5, vizslas: 7, cats: 1"),
        AuntSue::from(" perfumes: 1, trees: 6, goldfish: 0"),
        AuntSue::from(" goldfish: 6, trees: 10, cars: 10"),
        AuntSue::from(" akitas: 2, samoyeds: 6, trees: 9"),
        AuntSue::from(" vizslas: 4, akitas: 7, cars: 9"),
        AuntSue::from(" children: 3, perfumes: 4, cars: 1"),
        AuntSue::from(" akitas: 9, perfumes: 6, cars: 10"),
        AuntSue::from(" perfumes: 2, goldfish: 0, trees: 1"),
        AuntSue::from(" vizslas: 10, pomeranians: 7, goldfish: 6"),
        AuntSue::from(" trees: 3, vizslas: 8, cars: 3"),
        AuntSue::from(" akitas: 2, cats: 1, goldfish: 8"),
        AuntSue::from(" cars: 6, trees: 2, vizslas: 0"),
        AuntSue::from(" samoyeds: 7, cars: 7, trees: 3"),
        AuntSue::from(" cats: 7, children: 1, perfumes: 8"),
        AuntSue::from(" akitas: 5, goldfish: 10, vizslas: 5"),
        AuntSue::from(" cats: 3, vizslas: 0, akitas: 10"),
        AuntSue::from(" perfumes: 8, cars: 1, trees: 8"),
        AuntSue::from(" cars: 4, samoyeds: 8, children: 2"),
        AuntSue::from(" goldfish: 9, pomeranians: 1, samoyeds: 1"),
        AuntSue::from(" akitas: 3, trees: 0, goldfish: 2"),
        AuntSue::from(" perfumes: 4, vizslas: 8, pomeranians: 9"),
        AuntSue::from(" akitas: 4, cars: 5, goldfish: 4"),
        AuntSue::from(" samoyeds: 5, cats: 4, trees: 0"),
        AuntSue::from(" samoyeds: 4, cars: 8, akitas: 2"),
        AuntSue::from(" akitas: 3, vizslas: 10, perfumes: 10"),
        AuntSue::from(" goldfish: 10, akitas: 4, cars: 1"),
        AuntSue::from(" perfumes: 10, cats: 4, vizslas: 5"),
        AuntSue::from(" akitas: 2, vizslas: 4, cars: 7"),
        AuntSue::from(" akitas: 5, vizslas: 5, cars: 6"),
        AuntSue::from(" vizslas: 8, perfumes: 6, cars: 3"),
        AuntSue::from(" cars: 10, vizslas: 0, goldfish: 10"),
        AuntSue::from(" cars: 10, perfumes: 5, children: 7"),
        AuntSue::from(" vizslas: 6, akitas: 3, samoyeds: 9"),
        AuntSue::from(" akitas: 2, perfumes: 7, cars: 10"),
        AuntSue::from(" cars: 10, perfumes: 7, children: 6"),
        AuntSue::from(" akitas: 4, cars: 8, trees: 1"),
        AuntSue::from(" trees: 2, cars: 1, goldfish: 2"),
        AuntSue::from(" vizslas: 5, cars: 9, trees: 4"),
        AuntSue::from(" perfumes: 4, akitas: 3, cars: 3"),
        AuntSue::from(" children: 3, akitas: 2, cats: 5"),
        AuntSue::from(" cars: 8, cats: 4, akitas: 10"),
        AuntSue::from(" cats: 2, trees: 1, vizslas: 4"),
        AuntSue::from(" vizslas: 2, pomeranians: 5, samoyeds: 9"),
        AuntSue::from(" samoyeds: 2, akitas: 7, goldfish: 9"),
        AuntSue::from(" goldfish: 8, trees: 7, cats: 2"),
        AuntSue::from(" perfumes: 2, vizslas: 6, trees: 5"),
        AuntSue::from(" cars: 5, samoyeds: 0, perfumes: 6"),
        AuntSue::from(" samoyeds: 10, trees: 10, vizslas: 1"),
        AuntSue::from(" trees: 2, vizslas: 3, cars: 4"),
        AuntSue::from(" akitas: 6, pomeranians: 2, cats: 4"),
        AuntSue::from(" trees: 2, perfumes: 3, goldfish: 9"),
        AuntSue::from(" vizslas: 5, children: 0, pomeranians: 6"),
        AuntSue::from(" trees: 1, vizslas: 8, perfumes: 10"),
        AuntSue::from(" cars: 0, akitas: 6, children: 0"),
        AuntSue::from(" akitas: 1, vizslas: 0, trees: 0"),
        AuntSue::from(" samoyeds: 10, cats: 5, pomeranians: 0"),
        AuntSue::from(" goldfish: 3, pomeranians: 7, cats: 7"),
        AuntSue::from(" perfumes: 0, cats: 0, trees: 8"),
        AuntSue::from(" perfumes: 4, samoyeds: 1, akitas: 7"),
        AuntSue::from(" akitas: 4, pomeranians: 2, children: 4"),
        AuntSue::from(" vizslas: 9, akitas: 4, trees: 10"),
        AuntSue::from(" trees: 1, vizslas: 10, akitas: 6"),
        AuntSue::from(" trees: 3, akitas: 8, goldfish: 3"),
        AuntSue::from(" goldfish: 6, perfumes: 2, children: 9"),
        AuntSue::from(" children: 10, akitas: 7, goldfish: 7"),
        AuntSue::from(" goldfish: 3, vizslas: 10, perfumes: 5"),
        AuntSue::from(" children: 4, trees: 0, cars: 2"),
        AuntSue::from(" trees: 0, cats: 3, goldfish: 10"),
        AuntSue::from(" samoyeds: 9, pomeranians: 0, cats: 6"),
        AuntSue::from(" samoyeds: 10, trees: 3, akitas: 4"),
        AuntSue::from(" akitas: 9, goldfish: 10, perfumes: 7"),
        AuntSue::from(" goldfish: 6, cars: 2, akitas: 9"),
        AuntSue::from(" trees: 4, goldfish: 9, vizslas: 7"),
        AuntSue::from(" vizslas: 4, samoyeds: 1, goldfish: 6"),
        AuntSue::from(" vizslas: 5, cats: 0, samoyeds: 1"),
        AuntSue::from(" goldfish: 7, cats: 0, trees: 7"),
        AuntSue::from(" cars: 10, akitas: 1, vizslas: 7"),
        AuntSue::from(" samoyeds: 10, cats: 6, goldfish: 6"),
        AuntSue::from(" cats: 6, samoyeds: 0, trees: 2"),
        AuntSue::from(" trees: 1, children: 4, goldfish: 2"),
        AuntSue::from(" cats: 8, vizslas: 4, children: 3"),
        AuntSue::from(" cars: 9, perfumes: 8, pomeranians: 2"),
        AuntSue::from(" goldfish: 8, trees: 2, cars: 5"),
        AuntSue::from(" perfumes: 1, pomeranians: 5, vizslas: 5"),
        AuntSue::from(" perfumes: 6, trees: 2, pomeranians: 6"),
        AuntSue::from(" trees: 0, goldfish: 6, cars: 6"),
        AuntSue::from(" trees: 0, samoyeds: 7, goldfish: 9"),
        AuntSue::from(" samoyeds: 10, goldfish: 6, pomeranians: 0"),
        AuntSue::from(" perfumes: 5, vizslas: 6, trees: 0"),
        AuntSue::from(" goldfish: 2, trees: 2, pomeranians: 0"),
        AuntSue::from(" pomeranians: 4, perfumes: 8, cats: 8"),
        AuntSue::from(" vizslas: 4, cars: 5, akitas: 1"),
        AuntSue::from(" perfumes: 2, trees: 8, goldfish: 7"),
        AuntSue::from(" akitas: 3, trees: 1, perfumes: 3"),
        AuntSue::from(" cars: 7, trees: 1, perfumes: 8"),
        AuntSue::from(" cars: 5, goldfish: 5, trees: 1"),
        AuntSue::from(" cars: 9, goldfish: 4, samoyeds: 2"),
        AuntSue::from(" pomeranians: 8, akitas: 1, goldfish: 6"),
        AuntSue::from(" cars: 0, cats: 0, children: 8"),
        AuntSue::from(" akitas: 10, goldfish: 1, vizslas: 8"),
        AuntSue::from(" children: 8, vizslas: 6, samoyeds: 10"),
        AuntSue::from(" samoyeds: 3, goldfish: 10, vizslas: 8"),
        AuntSue::from(" cars: 3, children: 7, goldfish: 4"),
        AuntSue::from(" cars: 9, perfumes: 9, goldfish: 8"),
        AuntSue::from(" akitas: 5, trees: 10, vizslas: 10"),
        AuntSue::from(" vizslas: 10, cars: 3, akitas: 7"),
        AuntSue::from(" cats: 6, perfumes: 5, goldfish: 10"),
        AuntSue::from(" goldfish: 7, trees: 5, vizslas: 10"),
        AuntSue::from(" perfumes: 3, trees: 7, cars: 3"),
        AuntSue::from(" cars: 2, vizslas: 1, akitas: 6"),
        AuntSue::from(" pomeranians: 8, perfumes: 5, cars: 3"),
        AuntSue::from(" children: 8, cars: 0, perfumes: 7"),
        AuntSue::from(" samoyeds: 0, vizslas: 9, akitas: 10"),
        AuntSue::from(" akitas: 3, vizslas: 8, cats: 4"),
        AuntSue::from(" goldfish: 5, trees: 8, samoyeds: 8"),
        AuntSue::from(" cars: 10, samoyeds: 9, goldfish: 7"),
        AuntSue::from(" samoyeds: 5, akitas: 7, perfumes: 9"),
        AuntSue::from(" goldfish: 10, perfumes: 5, cars: 0"),
        AuntSue::from(" pomeranians: 1, samoyeds: 9, children: 4"),
        AuntSue::from(" vizslas: 4, perfumes: 2, cats: 5"),
        AuntSue::from(" trees: 0, pomeranians: 3, cars: 7"),
        AuntSue::from(" akitas: 0, cars: 2, vizslas: 10"),
        AuntSue::from(" children: 1, akitas: 9, trees: 0"),
        AuntSue::from(" cars: 5, perfumes: 7, goldfish: 9"),
        AuntSue::from(" akitas: 0, perfumes: 1, vizslas: 2"),
        AuntSue::from(" vizslas: 7, perfumes: 0, cars: 5"),
        AuntSue::from(" vizslas: 6, goldfish: 10, trees: 0"),
        AuntSue::from(" cars: 7, vizslas: 7, trees: 3"),
        AuntSue::from(" pomeranians: 4, akitas: 4, vizslas: 8"),
        AuntSue::from(" cats: 4, perfumes: 8, children: 3"),
        AuntSue::from(" samoyeds: 8, akitas: 9, cars: 1"),
        AuntSue::from(" cars: 8, akitas: 5, vizslas: 2"),
        AuntSue::from(" vizslas: 9, perfumes: 4, akitas: 4"),
        AuntSue::from(" akitas: 3, goldfish: 2, vizslas: 6"),
        AuntSue::from(" cars: 4, perfumes: 5, goldfish: 10"),
        AuntSue::from(" trees: 9, pomeranians: 4, goldfish: 10"),
        AuntSue::from(" pomeranians: 1, perfumes: 9, children: 6"),
        AuntSue::from(" samoyeds: 0, goldfish: 8, vizslas: 6"),
        AuntSue::from(" cars: 10, goldfish: 8, samoyeds: 8"),
        AuntSue::from(" akitas: 8, goldfish: 9, vizslas: 2"),
        AuntSue::from(" cars: 1, vizslas: 2, akitas: 8"),
        AuntSue::from(" goldfish: 2, akitas: 4, samoyeds: 10"),
        AuntSue::from(" children: 5, perfumes: 5, cars: 5"),
        AuntSue::from(" perfumes: 9, trees: 0, samoyeds: 6"),
        AuntSue::from(" akitas: 5, goldfish: 3, cats: 6"),
        AuntSue::from(" perfumes: 3, goldfish: 0, trees: 4"),
        AuntSue::from(" goldfish: 2, children: 4, trees: 1"),
        AuntSue::from(" cars: 0, perfumes: 8, children: 7"),
        AuntSue::from(" vizslas: 8, cats: 5, samoyeds: 9"),
        AuntSue::from(" pomeranians: 7, trees: 2, goldfish: 3"),
        AuntSue::from(" goldfish: 8, akitas: 4, perfumes: 5"),
        AuntSue::from(" perfumes: 2, pomeranians: 3, cars: 8"),
        AuntSue::from(" samoyeds: 0, akitas: 7, pomeranians: 6"),
        AuntSue::from(" vizslas: 7, perfumes: 1, trees: 6"),
        AuntSue::from(" vizslas: 3, samoyeds: 1, perfumes: 10"),
        AuntSue::from(" cars: 6, perfumes: 5, vizslas: 2"),
        AuntSue::from(" pomeranians: 1, goldfish: 3, akitas: 7"),
        AuntSue::from(" goldfish: 10, trees: 0, cars: 3"),
        AuntSue::from(" cats: 3, akitas: 5, vizslas: 8"),
        AuntSue::from(" pomeranians: 5, vizslas: 2, trees: 3"),
        AuntSue::from(" cars: 8, samoyeds: 10, goldfish: 10"),
        AuntSue::from(" pomeranians: 3, vizslas: 6, goldfish: 5"),
        AuntSue::from(" perfumes: 7, vizslas: 4, akitas: 7"),
        AuntSue::from(" goldfish: 1, trees: 0, perfumes: 10"),
        AuntSue::from(" goldfish: 6, perfumes: 0, akitas: 10"),
        AuntSue::from(" cats: 2, akitas: 10, trees: 1"),
        AuntSue::from(" akitas: 1, goldfish: 3, cars: 7"),
        AuntSue::from(" goldfish: 3, akitas: 6, vizslas: 6"),
        AuntSue::from(" goldfish: 8, perfumes: 2, akitas: 2"),
        AuntSue::from(" trees: 4, vizslas: 8, perfumes: 6"),
        AuntSue::from(" cars: 9, perfumes: 3, cats: 0"),
        AuntSue::from(" trees: 3, vizslas: 6, goldfish: 7"),
        AuntSue::from(" trees: 8, samoyeds: 1, perfumes: 5"),
        AuntSue::from(" children: 9, akitas: 8, vizslas: 4"),
        AuntSue::from(" vizslas: 2, pomeranians: 1, perfumes: 7"),
        AuntSue::from(" trees: 2, akitas: 4, vizslas: 6"),
        AuntSue::from(" akitas: 8, pomeranians: 7, trees: 0"),
        AuntSue::from(" perfumes: 6, goldfish: 3, vizslas: 7"),
        AuntSue::from(" cars: 1, perfumes: 6, vizslas: 1"),
    ]
}
